### ISSUE TITLE
go-get error: code.google.com/p/go-charset no go-import meta tags

### ISSUE THREAD

**Issue by mblakele** [mblakele/goread#2]
Thanks for this. I hope to continue using goread via my own app. But I can't seem to build using go 1.12. I get errors like this:

```
package code.google.com/p/go-charset/charset: unrecognized import path "code.google.com/p/go-charset/charset" (parse https://code.google.com/p/go-charset/charset?go-get=1: no go-import meta tags ())
package code.google.com/p/go-charset/data: unrecognized import path "code.google.com/p/go-charset/data" (parse https://code.google.com/p/go-charset/data?go-get=1: no go-import meta tags ())
```
I get the same when I use go 1.11.9. Any suggestions? Is there a better place to discuss this?

_Originally posted by @fredcy in https://github.com/mblakele/goread/pull/1#issuecomment-641415197_

**Comment by mblakele** [comment]
@fredcy looks like bitrot: I didn't run into it because I already had both packages, but if I delete them then `go get` fails for me with the same error. Not sure why, but I'll have a closer look.

Looks like go-charset has been deprecated for years. I found https://github.com/Sjeanpierre/passenger-datadog-monitor/issues/7 which suggests that https://godoc.org/golang.org/x/net/html/charset is a fairly clean replacement. I'm trying that now.

If that doesn't work, we might be able to use https://github.com/rogpeppe/go-charset but the author suggests migrating to https://godoc.org/golang.org/x/text/transform — and discussion at https://groups.google.com/forum/#!topic/Golang-nuts/FHmzYmM5r5Y also suggests https://godoc.org/golang.org/x/text/encoding

**Comment by fredcy** [comment]
Thanks so much for looking into this!  I spend probably 30 minutes a day using goread over the last 5 years and I will be happy to keep it going.

I will pull this new code and give it a go. I had tried replacing with "github.com/rogpeppe/go-charset" but it seems that you have worked out a better solution.
